conda_install_tool: pixi
conda_build_tool: rattler-build
recipe_dir: recipe
build_platform:
    linux_ppc64le: linux_64
    linux_aarch64: linux_64
    osx_64: linux_64
    osx_arm64: linux_64
    win_64: linux_64
github:
    branch_name: main
test: native
