name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linux-64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - name: Build
        shell: bash
        run: pixi run build-locally linux_64_
  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - name: Build
        shell: bash
        run: pixi run build-locally linux_aarch64_
  # osx-arm64:
  #   runs-on: osx-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: prefix-dev/setup-pixi@v0.9.0
  #     - name: Build
  #       shell: bash
  #       run: pixi run build-locally osx_arm64_
  # win_64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: prefix-dev/setup-pixi@v0.9.0
  #     - name: Build
  #       shell: bash
  #       run: pixi run build-locally win_64_
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: prefix-dev/setup-pixi@v0.9.0
  #     - name: Build
  #       shell: bash
  #       run: |
  #         pixi run build
  #     - name: Caching object files
  #       uses: actions/cache@v4
  #       with:
  #         key: demo-to-be-changed
  #         path: ./out
