name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-locally:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - name: Build
        shell: bash
        run: pixi run build-locally
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
      - name: Build
        shell: bash
        run: |
          pixi run build
      - name: Caching object files
        uses: actions/cache@v4
        with:
          key: demo-to-be-changed
          path: ./out
